### ISSUE TITLE
Format the mitre_attack_csv.py

### ISSUE THREAD

**Issue by stmtstk** [stmtstk/mitre_attack_csv#29]
After using `super_linter` automation, `mitre_attack_csv.py` format check fails.
We should modify the `mitre_attack_csv.py` to pass the check.

**Comment by stmtstk** [comment]
In the current setting, `super_linter` tries to five format checks for a python file.

- pylint
- flake8
- mypy
- black
- isort

I think, it is redundant. We should disable `pylint`, `black`, `isort` checks.
Additionally, I will set a flake8 rule and ignore `E501` rule (Too long line).

**Comment by stmtstk** [comment]
https://gist.github.com/stmtstk/33516e7639394b3070e4151ac9975094

I modified `mitre_attack_csv.py` for `super_linter` checks.

- Add docstring for each function
- Sort the import module
- Add exception (`except IOError` instead of `except`)

> @shiracamus 
Could you check the docstring whether this format is right or not?

> @rmasuoka 
Could you check the docstring from English grammar aspect?

**Comment by shiracamus** [comment]
Use triple-double-quote for docstring .
A blink line is needed between explain and parameters.
Check https://peps.python.org/pep-0257/

**Comment by stmtstk** [comment]
Thanks, @shiracamus .

I replaced the quote marks.

**Comment by stmtstk** [comment]
I also add the encoding options for open file.
https://gist.github.com/stmtstk/33516e7639394b3070e4151ac9975094#file-mitre_attack_csv-py-L37

**Comment by shiracamus** [comment]
The comment at top of the file should explain the function, command usage etc.

**Comment by stmtstk** [comment]
Add the docstring below.

```
""" Generate csv files from MITRE ATT&CK STIX content
    options
    --attack_id: add mitre_attack_id column
    --attack_version: specify ATT&CK version to use (default: 11.3)
    --version: ouput this module version
"""
```

**Comment by stmtstk** [comment]
Insert a newline.
```python
""" Generate csv files from MITRE ATT&CK STIX content
    options
    --attack_id: add mitre_attack_id column
    --attack_version: specify ATT&CK version to use (default: 11.3)
    --version: ouput this module version
"""
```

**Comment by stmtstk** [comment]
Insert new lines for each functions

```
    """ Load STIX content from local file

    :returns: ATT&CK STIX JSON
    :rtype: Optional[Attack]
    """
```

**Comment by stmtstk** [comment]
Modify the description of `get_fields`

```python
    """ Get filed data from a specified object.

    If the object has external_id of ATT&CK object ID, this function add the ID.

    :param names: CSV Header List
    :type names: Header
    :param attack: ATT&CK STIX JSON
    :type attack: Attack
    :retruns: CSV record
    :rtype: Attack
    """
```
