### ISSUE TITLE
Add ATT&CK version numbers to the CSV files

### ISSUE THREAD

**Issue by rmasuoka** [stmtstk/mitre_attack_csv#32]
Add ATT&CK version numbers to the CSV files

When the CSV files are downloaded locally, it is difficult to tell which version of ATT&CK the CSV files came from without version numbers in their filenames. .

**Comment by rmasuoka** [comment]
You do not need to update the shell script to produce index.html in each ATT&CK CSV folder. (The shell script uses filenames in the folder.)

**Comment by stmtstk** [comment]
I have already merged all other previous pull requests.
Fetch this repo, pull into your `main` branch.
