### ISSUE TITLE
No "CSV files WITH ATT&CK ID" info in index.html for CSV folders

### ISSUE THREAD

**Issue by rmasuoka** [stmtstk/mitre_attack_csv#35]
There seems no "CSV files WITH ATT&CK ID" info in index.html for CSV folders. For example, see https://stmtstk.github.io/mitre_attack_csv/attack-csv-data/v11.3/

**Comment by rmasuoka** [comment]
I checked produce-index.sh and the script tries to find "*-w-id.csv", but the files have version numbers just in front of their extension like  "attack-pattern-w-id-v11.3.csv." I would like @Yuya670 to check it and fix it (it should be a very quick fix).

**Comment by Yuya670** [comment]
I will check it soon.

**Comment by rmasuoka** [comment]
Thanks! (No rush, though)
